language: php 

compiler:
  - gcc
  - clang

os:
  - linux

php:
  - 7.2
  - 7.3
  - 8.1

notifications:
  email: bob_zy@yeah.net

install:
   - composer install --no-interaction --prefer-dist
  
before_script:
    - phpize && ./configure && make && make install
    - echo "extension = phptars.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
    - cd testcases 
    - php ../vendor/bin/phpunit --fail-on-warning test.php
    - php ../vendor/bin/phpunit --fail-on-warning testTARSClient.php
    - php ../vendor/bin/phpunit --fail-on-warning testTARSServer.php

